<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class image_jobs_seed extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $imageJobs = [
            [
                'id' => 1,
                'user_id' => 1,
                'feature_id' => 1,
                'prompt' => '1girl, cute, smile, beautiful, detailed, high quality',
                'width' => 512,
                'height' => 768,
                'seed' => 123456789,
                'style' => 'realistic',
                'main_image' => null,
                'secondary_image' => null,
                'result_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/images/sample1.jpg',
                'status' => 'completed',
                'comfy_prompt_id' => 'prompt_001',
                'error_message' => null,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'id' => 2,
                'user_id' => 2,
                'feature_id' => 2,
                'prompt' => 'anime style, 1girl, blue hair, school uniform, detailed',
                'width' => 512,
                'height' => 768,
                'seed' => 987654321,
                'style' => 'anime',
                'main_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/input/sample_input.jpg',
                'secondary_image' => null,
                'result_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/images/sample2.jpg',
                'status' => 'completed',
                'comfy_prompt_id' => 'prompt_002',
                'error_message' => null,
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(4),
            ],
            [
                'id' => 3,
                'user_id' => 3,
                'feature_id' => 3,
                'prompt' => 'landscape, sunset, mountains, beautiful nature, realistic',
                'width' => 1024,
                'height' => 768,
                'seed' => 456789123,
                'style' => 'realistic',
                'main_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/input/landscape1.jpg',
                'secondary_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/input/landscape2.jpg',
                'result_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/images/sample3.jpg',
                'status' => 'completed',
                'comfy_prompt_id' => 'prompt_003',
                'error_message' => null,
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'id' => 4,
                'user_id' => 4,
                'feature_id' => 4,
                'prompt' => 'sketch to image, line art, colorful, detailed',
                'width' => 512,
                'height' => 512,
                'seed' => 789123456,
                'style' => 'artistic',
                'main_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/input/sketch1.jpg',
                'secondary_image' => null,
                'result_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/images/sample4.jpg',
                'status' => 'completed',
                'comfy_prompt_id' => 'prompt_004',
                'error_message' => null,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'id' => 5,
                'user_id' => 5,
                'feature_id' => 5,
                'prompt' => 'anime conversion, 1girl, pink hair, detailed face',
                'width' => 512,
                'height' => 768,
                'seed' => 321654987,
                'style' => 'anime',
                'main_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/input/portrait1.jpg',
                'secondary_image' => null,
                'result_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/images/sample5.jpg',
                'status' => 'completed',
                'comfy_prompt_id' => 'prompt_005',
                'error_message' => null,
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
            [
                'id' => 6,
                'user_id' => 6,
                'feature_id' => 6,
                'prompt' => 'cute 3D character, chibi style, pastel colors',
                'width' => 512,
                'height' => 512,
                'seed' => 147258369,
                'style' => '3d',
                'main_image' => null,
                'secondary_image' => null,
                'result_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/images/sample6.jpg',
                'status' => 'completed',
                'comfy_prompt_id' => 'prompt_006',
                'error_message' => null,
                'created_at' => now()->subHours(12),
                'updated_at' => now()->subHours(12),
            ],
            [
                'id' => 7,
                'user_id' => 7,
                'feature_id' => 1,
                'prompt' => 'fantasy landscape, magical forest, glowing mushrooms',
                'width' => 1024,
                'height' => 768,
                'seed' => 963852741,
                'style' => 'fantasy',
                'main_image' => null,
                'secondary_image' => null,
                'result_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/images/sample7.jpg',
                'status' => 'completed',
                'comfy_prompt_id' => 'prompt_007',
                'error_message' => null,
                'created_at' => now()->subHours(6),
                'updated_at' => now()->subHours(6),
            ],
            [
                'id' => 8,
                'user_id' => 8,
                'feature_id' => 2,
                'prompt' => 'portrait, professional, business suit, confident pose',
                'width' => 512,
                'height' => 768,
                'seed' => 852963741,
                'style' => 'realistic',
                'main_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/input/portrait2.jpg',
                'secondary_image' => null,
                'result_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/images/sample8.jpg',
                'status' => 'completed',
                'comfy_prompt_id' => 'prompt_008',
                'error_message' => null,
                'created_at' => now()->subHours(3),
                'updated_at' => now()->subHours(3),
            ],
            [
                'id' => 9,
                'user_id' => 9,
                'feature_id' => 3,
                'prompt' => 'cyberpunk city, neon lights, futuristic architecture',
                'width' => 1024,
                'height' => 768,
                'seed' => 741852963,
                'style' => 'cyberpunk',
                'main_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/input/city1.jpg',
                'secondary_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/input/city2.jpg',
                'result_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/images/sample9.jpg',
                'status' => 'completed',
                'comfy_prompt_id' => 'prompt_009',
                'error_message' => null,
                'created_at' => now()->subHours(1),
                'updated_at' => now()->subHours(1),
            ],
            [
                'id' => 10,
                'user_id' => 10,
                'feature_id' => 4,
                'prompt' => 'watercolor style, flowers, spring, soft colors',
                'width' => 512,
                'height' => 512,
                'seed' => 369258147,
                'style' => 'watercolor',
                'main_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/input/flower_sketch.jpg',
                'secondary_image' => null,
                'result_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/images/sample10.jpg',
                'status' => 'completed',
                'comfy_prompt_id' => 'prompt_010',
                'error_message' => null,
                'created_at' => now()->subMinutes(30),
                'updated_at' => now()->subMinutes(30),
            ],
            
            // Một số job đang xử lý
            [
                'id' => 11,
                'user_id' => 1,
                'feature_id' => 1,
                'prompt' => '1boy, handsome, suit, office, professional',
                'width' => 512,
                'height' => 768,
                'seed' => 123789456,
                'style' => 'realistic',
                'main_image' => null,
                'secondary_image' => null,
                'result_image' => null,
                'status' => 'processing',
                'comfy_prompt_id' => 'prompt_011',
                'error_message' => null,
                'created_at' => now()->subMinutes(5),
                'updated_at' => now()->subMinutes(5),
            ],
            [
                'id' => 12,
                'user_id' => 2,
                'feature_id' => 2,
                'prompt' => 'anime girl, pink hair, school uniform, cute',
                'width' => 512,
                'height' => 768,
                'seed' => 987321654,
                'style' => 'anime',
                'main_image' => 'https://pub-ed515111f589440fb333ebcd308ee890.r2.dev/input/anime_input.jpg',
                'secondary_image' => null,
                'result_image' => null,
                'status' => 'pending',
                'comfy_prompt_id' => null,
                'error_message' => null,
                'created_at' => now()->subMinutes(2),
                'updated_at' => now()->subMinutes(2),
            ],
            
            // Một số job thất bại
            [
                'id' => 13,
                'user_id' => 3,
                'feature_id' => 1,
                'prompt' => 'invalid prompt with special characters @#$%',
                'width' => 512,
                'height' => 768,
                'seed' => 456123789,
                'style' => 'realistic',
                'main_image' => null,
                'secondary_image' => null,
                'result_image' => null,
                'status' => 'failed',
                'comfy_prompt_id' => 'prompt_013',
                'error_message' => 'Invalid prompt format. Special characters not allowed.',
                'created_at' => now()->subHours(2),
                'updated_at' => now()->subHours(2),
            ],
            [
                'id' => 14,
                'user_id' => 4,
                'feature_id' => 3,
                'prompt' => 'landscape, mountains, sunset',
                'width' => 2048,
                'height' => 2048,
                'seed' => 789456123,
                'style' => 'realistic',
                'main_image' => null,
                'secondary_image' => null,
                'result_image' => null,
                'status' => 'failed',
                'comfy_prompt_id' => 'prompt_014',
                'error_message' => 'Image dimensions too large. Maximum allowed: 1024x1024',
                'created_at' => now()->subHours(1),
                'updated_at' => now()->subHours(1),
            ],
        ];

        DB::table('image_jobs')->insert($imageJobs);
    }
} 