<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class interactions_seed extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $interactions = [
            // Likes cho image 1
            [
                'id' => 1,
                'user_id' => 2,
                'image_id' => 1,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(4),
            ],
            [
                'id' => 2,
                'user_id' => 3,
                'image_id' => 1,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'id' => 3,
                'user_id' => 4,
                'image_id' => 1,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            
            // Likes cho image 2
            [
                'id' => 4,
                'user_id' => 1,
                'image_id' => 2,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'id' => 5,
                'user_id' => 3,
                'image_id' => 2,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'id' => 6,
                'user_id' => 5,
                'image_id' => 2,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
            [
                'id' => 7,
                'user_id' => 6,
                'image_id' => 2,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(12),
                'updated_at' => now()->subHours(12),
            ],
            
            // Likes cho image 3
            [
                'id' => 8,
                'user_id' => 1,
                'image_id' => 3,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'id' => 9,
                'user_id' => 2,
                'image_id' => 3,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
            [
                'id' => 10,
                'user_id' => 4,
                'image_id' => 3,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(18),
                'updated_at' => now()->subHours(18),
            ],
            [
                'id' => 11,
                'user_id' => 5,
                'image_id' => 3,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(12),
                'updated_at' => now()->subHours(12),
            ],
            [
                'id' => 12,
                'user_id' => 6,
                'image_id' => 3,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(6),
                'updated_at' => now()->subHours(6),
            ],
            
            // Saves cho image 1
            [
                'id' => 13,
                'user_id' => 2,
                'image_id' => 1,
                'type_interaction' => 'save',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'id' => 14,
                'user_id' => 5,
                'image_id' => 1,
                'type_interaction' => 'save',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
            
            // Saves cho image 3
            [
                'id' => 15,
                'user_id' => 1,
                'image_id' => 3,
                'type_interaction' => 'save',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
            [
                'id' => 16,
                'user_id' => 7,
                'image_id' => 3,
                'type_interaction' => 'save',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(12),
                'updated_at' => now()->subHours(12),
            ],
            
            // Likes cho image 4
            [
                'id' => 17,
                'user_id' => 1,
                'image_id' => 4,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
            [
                'id' => 18,
                'user_id' => 3,
                'image_id' => 4,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(8),
                'updated_at' => now()->subHours(8),
            ],
            [
                'id' => 19,
                'user_id' => 6,
                'image_id' => 4,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(4),
                'updated_at' => now()->subHours(4),
            ],
            
            // Likes cho image 5
            [
                'id' => 20,
                'user_id' => 2,
                'image_id' => 5,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(8),
                'updated_at' => now()->subHours(8),
            ],
            [
                'id' => 21,
                'user_id' => 4,
                'image_id' => 5,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(6),
                'updated_at' => now()->subHours(6),
            ],
            [
                'id' => 22,
                'user_id' => 7,
                'image_id' => 5,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(2),
                'updated_at' => now()->subHours(2),
            ],
            
            // Likes cho image 6
            [
                'id' => 23,
                'user_id' => 1,
                'image_id' => 6,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(10),
                'updated_at' => now()->subHours(10),
            ],
            [
                'id' => 24,
                'user_id' => 3,
                'image_id' => 6,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(8),
                'updated_at' => now()->subHours(8),
            ],
            [
                'id' => 25,
                'user_id' => 5,
                'image_id' => 6,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(5),
                'updated_at' => now()->subHours(5),
            ],
            [
                'id' => 26,
                'user_id' => 8,
                'image_id' => 6,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(3),
                'updated_at' => now()->subHours(3),
            ],
            
            // Likes cho image 7
            [
                'id' => 27,
                'user_id' => 2,
                'image_id' => 7,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(4),
                'updated_at' => now()->subHours(4),
            ],
            [
                'id' => 28,
                'user_id' => 4,
                'image_id' => 7,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(3),
                'updated_at' => now()->subHours(3),
            ],
            [
                'id' => 29,
                'user_id' => 6,
                'image_id' => 7,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(2),
                'updated_at' => now()->subHours(2),
            ],
            [
                'id' => 30,
                'user_id' => 8,
                'image_id' => 7,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(1),
                'updated_at' => now()->subHours(1),
            ],
            
            // Saves cho image 7
            [
                'id' => 31,
                'user_id' => 1,
                'image_id' => 7,
                'type_interaction' => 'save',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(2),
                'updated_at' => now()->subHours(2),
            ],
            [
                'id' => 32,
                'user_id' => 9,
                'image_id' => 7,
                'type_interaction' => 'save',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(1),
                'updated_at' => now()->subHours(1),
            ],
            
            // Likes cho image 9
            [
                'id' => 33,
                'user_id' => 1,
                'image_id' => 9,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subMinutes(45),
                'updated_at' => now()->subMinutes(45),
            ],
            [
                'id' => 34,
                'user_id' => 3,
                'image_id' => 9,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subMinutes(30),
                'updated_at' => now()->subMinutes(30),
            ],
            [
                'id' => 35,
                'user_id' => 5,
                'image_id' => 9,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subMinutes(15),
                'updated_at' => now()->subMinutes(15),
            ],
            [
                'id' => 36,
                'user_id' => 7,
                'image_id' => 9,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subMinutes(10),
                'updated_at' => now()->subMinutes(10),
            ],
            [
                'id' => 37,
                'user_id' => 10,
                'image_id' => 9,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subMinutes(5),
                'updated_at' => now()->subMinutes(5),
            ],
            
            // Likes cho image 10
            [
                'id' => 38,
                'user_id' => 2,
                'image_id' => 10,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subMinutes(15),
                'updated_at' => now()->subMinutes(15),
            ],
            [
                'id' => 39,
                'user_id' => 4,
                'image_id' => 10,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subMinutes(10),
                'updated_at' => now()->subMinutes(10),
            ],
            [
                'id' => 40,
                'user_id' => 6,
                'image_id' => 10,
                'type_interaction' => 'like',
                'content' => '',
                'status_interaction' => 'active',
                'created_at' => now()->subMinutes(5),
                'updated_at' => now()->subMinutes(5),
            ],
            
            // Report cho image 8 (private image)
            [
                'id' => 41,
                'user_id' => 1,
                'image_id' => 8,
                'type_interaction' => 'report',
                'content' => 'Nội dung không phù hợp',
                'status_interaction' => 'active',
                'created_at' => now()->subHours(2),
                'updated_at' => now()->subHours(2),
            ],
        ];

        DB::table('interactions')->insert($interactions);
    }
} 